### ISSUE TITLE
FAQ - Add I want to create a conda package for my project. Where do I start? question

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#55]
## Description

Add the question "I want to create a conda package for my project. Where do I start?" to the conda.org FAQ (docs/faq.md) and answer it.

**Comment by NIKITA-M-VERMA** [comment]
Hello @travishathaway  and @kathatherine
I find this issue to be very interesting, and I would like to know if I could potentially contribute to it.
Could you please let me know if this issue is currently assigned to someone else, or if it is still open for anyone to take up? If it is available, I would be thrilled to work on it and make a meaningful contribution to the project.

I look forward to hearing back from you soon
